package com.suvojeet.suvmusic.ui.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.suvojeet.suvmusic.core.model.Song
import com.suvojeet.suvmusic.core.model.HomeSection
import com.suvojeet.suvmusic.core.model.HomeItem
import com.suvojeet.suvmusic.core.model.HomeSectionType
import com.suvojeet.suvmusic.data.repository.JioSaavnRepository
import com.suvojeet.suvmusic.data.repository.YouTubeRepository
import com.suvojeet.suvmusic.data.SessionManager
import com.suvojeet.suvmusic.recommendation.RecommendationEngine
import com.suvojeet.suvmusic.data.MusicSource
import com.suvojeet.suvmusic.lastfm.LastFmRepository
import com.suvojeet.suvmusic.lastfm.RecommendedArtist
import com.suvojeet.suvmusic.lastfm.RecommendedTrack
import com.suvojeet.suvmusic.player.MusicPlayer
import com.suvojeet.suvmusic.data.repository.DownloadRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import javax.inject.Inject

sealed class HomeEvent {
    data class ShowAddToPlaylistSheet(val song: Song) : HomeEvent()
    object ScrollToTop : HomeEvent()
    object Refresh : HomeEvent()
}

data class HomeUiState(
    val homeSections: List<HomeSection> = emptyList(),
    val filteredSections: List<HomeSection> = emptyList(),
    val recommendations: List<Song> = emptyList(),
    /** Personalized sections generated by RecommendationEngine (artist mixes, discovery, etc.) */
    val personalizedSections: List<HomeSection> = emptyList(),
    /** Genre-based discovery sections ("Because you like Pop", "Your Indie Mix", etc.) */
    val genreSections: List<HomeSection> = emptyList(),
    /** Context-aware sections (time-of-day, mood-detected, listening patterns) */
    val contextSections: List<HomeSection> = emptyList(),
    /** Additional sections loaded via scroll-to-load (varied styles, taste-driven) */
    val moreSections: List<HomeSection> = emptyList(),
    val recommendedArtists: List<RecommendedArtist> = emptyList(),
    val recommendedTracks: List<RecommendedTrack> = emptyList(),
    val userAvatarUrl: String? = null,
    val isLoading: Boolean = false,
    val isRefreshing: Boolean = false,
    /** True when loading additional sections at the bottom */
    val isLoadingMore: Boolean = false,
    val error: String? = null,
    val currentSource: MusicSource = MusicSource.YOUTUBE,
    val selectedMood: String? = null,
    /** Whether the user is logged in (for showing personalized content) */
    val isLoggedIn: Boolean = false,
    /** How many "load more" pages have been fetched (for infinite scroll) */
    val loadMorePage: Int = 0,
    /** True when no more sections can be loaded */
    val hasReachedEnd: Boolean = false,
    /** Detected current mood based on listening patterns */
    val detectedMood: String? = null,
    /** Whether the "Made for You" banner should be shown */
    val isForYouBannerVisible: Boolean = true,
    /** Configuration for home screen sections visibility */
    val homeSectionsVisibility: Set<String> = SessionManager.DEFAULT_HOME_SECTIONS
)

class HomeViewModel @Inject constructor(
    private val youTubeRepository: YouTubeRepository,
    private val jioSaavnRepository: JioSaavnRepository,
    private val sessionManager: SessionManager,
    private val recommendationEngine: RecommendationEngine,
    private val lastFmRepository: LastFmRepository,
    private val musicPlayer: MusicPlayer,
    private val downloadRepository: DownloadRepository
) : ViewModel() {
    
    private val _uiState = MutableStateFlow(HomeUiState())
    val uiState: StateFlow<HomeUiState> = _uiState.asStateFlow()

    private val _events = MutableSharedFlow<HomeEvent>()
    val events: SharedFlow<HomeEvent> = _events.asSharedFlow()
    
    init {
        // 1. Immutable observations (continuous flows)
        observeSession()
        observeMusicSource()
        observeForYouBanner()
        observeHomeSectionsVisibility()
        
        // 2. Structured data loading
        loadHomeContent()
    }

    private fun observeHomeSectionsVisibility() {
        viewModelScope.launch {
            sessionManager.homeSectionsVisibilityFlow.collect { visibility ->
                _uiState.update { it.copy(homeSectionsVisibility = visibility) }
            }
        }
    }
    
    /**
     * Entry point for all home-related data loading.
     * Launches a single coroutine to coordinate multiple data sources and avoid over-allocation.
     */
    private fun loadHomeContent(forceRefresh: Boolean = false) {
        viewModelScope.launch {
            // 1. Prioritize base data (HomeSections from YouTube/JioSaavn)
            loadData(forceRefresh)
            
            // 2. Stagger background taste-profile-driven content with larger delays to prevent memory spikes
            kotlinx.coroutines.delay(2000L) 
            launch { loadRecommendations() }
            
            kotlinx.coroutines.delay(1500L)
            launch { loadPersonalizedSections() }
            
            // 3. Further stagger secondary metadata and low-priority detections.
            kotlinx.coroutines.delay(2000L)
            launch { loadGenreSections() }
            
            kotlinx.coroutines.delay(1500L)
            launch { loadContextSections() }
            
            kotlinx.coroutines.delay(1500L)
            launch { loadLastFmRecommendations() }
            launch { detectMood() }
        }
    }

    override fun onCleared() {
        super.onCleared()
        // Clear memory-heavy recommendation caches when leaving Home
        recommendationEngine.onAuthStateChanged() // This clears all caches
    }
    
    private fun observeSession() {
        viewModelScope.launch {
            sessionManager.userAvatarFlow.collect { avatarUrl ->
                _uiState.update { it.copy(
                    userAvatarUrl = avatarUrl,
                    isLoggedIn = sessionManager.isLoggedIn()
                ) }
            }
        }
    }

    private fun observeForYouBanner() {
        viewModelScope.launch {
            sessionManager.forYouBannerDismissedAtFlow.collect { dismissedAt ->
                val sevenDaysInMillis = 7 * 24 * 60 * 60 * 1000L
                val shouldShow = System.currentTimeMillis() - dismissedAt > sevenDaysInMillis
                _uiState.update { it.copy(isForYouBannerVisible = shouldShow) }
            }
        }
    }

    fun onDismissForYouBanner() {
        viewModelScope.launch {
            sessionManager.setForYouBannerDismissedAt(System.currentTimeMillis())
        }
    }
    
    private fun observeMusicSource() {
        viewModelScope.launch {
            sessionManager.musicSourceFlow.collect { source ->
                val currentSource = _uiState.value.currentSource
                if (source != currentSource) {
                    _uiState.update { it.copy(currentSource = source) }
                    loadData() // Reload when source changes
                }
            }
        }
    }

    fun onMoodSelected(mood: String) {
        val currentMood = _uiState.value.selectedMood
        if (currentMood == mood) {
            // Deselect and reload default home
            _uiState.update { it.copy(selectedMood = null) }
            loadData(forceRefresh = true) 
        } else {
            // Select new mood
            _uiState.update { it.copy(selectedMood = mood) }
            fetchMoodContent(mood)
        }
    }

    private fun fetchMoodContent(mood: String) {
        viewModelScope.launch {
            _uiState.update { it.copy(isLoading = true, error = null) }
            try {
                // Determine source (JioSaavn usually doesn't have this granular mood flow implemented yet, but fallback to search works)
                val sections = if (_uiState.value.currentSource == MusicSource.JIOSAAVN) {
                     // Simple fallback for JioSaavn
                     val songs = jioSaavnRepository.search(mood)
                     listOf(
                         HomeSection(
                             title = "$mood Music",
                             items = songs.map { HomeItem.SongItem(it) },
                             type = HomeSectionType.VerticalList
                         )
                     )
                } else {
                    youTubeRepository.getHomeSectionsForMood(mood)
                }

                _uiState.update { 
                    it.copy(
                        homeSections = sections,
                        filteredSections = sections.filter { s -> !s.title.contains("Quick picks", ignoreCase = true) },
                        isLoading = false,
                        isRefreshing = false,
                        error = if (sections.isEmpty()) "No content found for $mood" else null
                    )
                }
            } catch (e: Exception) {
                _uiState.update { 
                    it.copy(
                        isLoading = false, 
                        error = e.message
                    ) 
                }
            }
        }
    }
    
    private fun loadData(forceRefresh: Boolean = false) {
        if (_uiState.value.selectedMood != null && !forceRefresh) return

        viewModelScope.launch {
            val source = sessionManager.getMusicSource()
            _uiState.update { it.copy(currentSource = source) }
            
            // 1. Load Cache Synchronously (from DataStore first emission)
            val cachedSections = if (source == MusicSource.JIOSAAVN) {
                sessionManager.getCachedJioSaavnHomeSections().first()
            } else {
                sessionManager.getCachedHomeSections().first()
            }
            
            val cachedQuickPicks = sessionManager.getCachedQuickPicks().first()
            
            if (cachedSections.isNotEmpty() || cachedQuickPicks.isNotEmpty()) {
                _uiState.update { 
                    it.copy(
                        homeSections = cachedSections, 
                        filteredSections = cachedSections.filter { s -> !s.title.contains("Quick picks", ignoreCase = true) },
                        recommendations = cachedQuickPicks,
                        isLoading = false,
                        error = null
                    ) 
                }
            } else {
                _uiState.update { it.copy(isLoading = true) }
            }
            
            // 2. Throttled Fresh Data Fetching
            val lastFetchTime = sessionManager.getLastHomeFetchTime(source)
            val cooldown = 30 * 60 * 1000L // 30 minutes cooldown
            val isCooldownActive = System.currentTimeMillis() - lastFetchTime < cooldown
            
            // Only fetch if forced, cooldown expired, or we have absolutely no data
            if (forceRefresh || !isCooldownActive || _uiState.value.homeSections.isEmpty()) {
                fetchFreshData(source)
            } else {
                _uiState.update { it.copy(isLoading = false, isRefreshing = false) }
            }
        }
    }

    private suspend fun fetchFreshData(source: MusicSource) {
        try {
            _uiState.update { it.copy(isRefreshing = true) }
            val sections = when (source) {
                MusicSource.JIOSAAVN -> jioSaavnRepository.getHomeSections()
                else -> youTubeRepository.getHomeSections()
            }
            
            if (sections.isNotEmpty()) {
                _uiState.update { 
                    it.copy(
                        homeSections = sections,
                        filteredSections = sections.filter { s -> !s.title.contains("Quick picks", ignoreCase = true) },
                        isLoading = false,
                        isRefreshing = false,
                        error = null
                    ) 
                }
                sessionManager.updateLastHomeFetchTime(source)
                
                // Save to cache asynchronously
                if (source == MusicSource.JIOSAAVN) {
                    sessionManager.saveJioSaavnHomeCache(sections)
                } else {
                    sessionManager.saveHomeCache(sections)
                }
            } else {
                _uiState.update { it.copy(isLoading = false, isRefreshing = false) }
            }
        } catch (e: Exception) {
            _uiState.update { 
                it.copy(
                    error = if (it.homeSections.isEmpty()) e.message ?: "Failed to load content" else null,
                    isLoading = false,
                    isRefreshing = false
                ) 
            }
        }
    }
    
    fun scrollToTop() {
        viewModelScope.launch {
            _events.emit(HomeEvent.ScrollToTop)
        }
    }

    fun triggerRefresh() {
        viewModelScope.launch {
            _events.emit(HomeEvent.Refresh)
            refresh()
        }
    }
    
    fun refresh() {
        // Invalidate recommendation caches for fresh data
        recommendationEngine.onAuthStateChanged()
        
        // Reset infinite scroll state
        loadMoreRetryCount = 0
        _uiState.update { 
            it.copy(
                loadMorePage = 0, 
                hasReachedEnd = false, 
                moreSections = emptyList(),
                isRefreshing = true 
            ) 
        }
        
        // Trigger structured reload
        loadHomeContent(forceRefresh = true)
    }
    
    private fun loadRecommendations() {
        viewModelScope.launch {
            try {
                // Use the enhanced recommendation engine for Quick Picks
                val recommendations = recommendationEngine.getPersonalizedRecommendations(20)
                _uiState.update { it.copy(recommendations = recommendations) }
                
                // Save to cache
                if (recommendations.isNotEmpty()) {
                    sessionManager.saveQuickPicksCache(recommendations)
                }
            } catch (e: Exception) {
                // Silently fail - recommendations are optional
                _uiState.update { it.copy(recommendations = emptyList()) }
            }
        }
    }

    /**
     * Load personalized sections (artist mixes, discovery, forgotten favorites, time-based).
     * These are generated by the RecommendationEngine and provide deep personalization.
     */
    private fun loadPersonalizedSections() {
        viewModelScope.launch {
            try {
                val sections = recommendationEngine.getPersonalizedHomeSections()
                // Filter out "Quick picks" since it's shown separately
                val extraSections = sections.filter { 
                    !it.title.equals("Quick picks", ignoreCase = true) 
                }
                _uiState.update { it.copy(personalizedSections = extraSections) }
            } catch (e: Exception) {
                _uiState.update { it.copy(personalizedSections = emptyList()) }
            }
        }
    }

    private fun loadLastFmRecommendations() {
        viewModelScope.launch {
            if (!sessionManager.isLastFmRecommendationsEnabled()) {
                _uiState.update { it.copy(recommendedArtists = emptyList(), recommendedTracks = emptyList()) }
                return@launch
            }
            
            val sessionKey = sessionManager.getLastFmSessionKey()
            if (sessionKey != null) {
                // Fetch Artists
                launch {
                    lastFmRepository.getRecommendedArtists(sessionKey)
                        .onSuccess { response ->
                            _uiState.update { it.copy(recommendedArtists = response.recommendations.artist) }
                        }
                        .onFailure {
                            _uiState.update { it.copy(recommendedArtists = emptyList()) }
                        }
                }
                
                // Fetch Tracks
                launch {
                    lastFmRepository.getRecommendedTracks(sessionKey)
                        .onSuccess { response ->
                            _uiState.update { it.copy(recommendedTracks = response.tracks.track) }
                        }
                        .onFailure {
                             _uiState.update { it.copy(recommendedTracks = emptyList()) }
                        }
                }
            } else {
                _uiState.update { it.copy(recommendedArtists = emptyList(), recommendedTracks = emptyList()) }
            }
        }
    }

    fun playNext(song: Song) {
        musicPlayer.playNext(listOf(song))
    }

    fun addToQueue(song: Song) {
        musicPlayer.addToQueue(listOf(song))
    }

    fun downloadSong(song: Song) {
        viewModelScope.launch {
            downloadRepository.downloadSong(song)
        }
    }

    fun addToPlaylist(song: Song) {
        viewModelScope.launch {
            _events.emit(HomeEvent.ShowAddToPlaylistSheet(song))
        }
    }

    /**
     * Start a "Random Mix" based on the user's personalized recommendations.
     * Fetches a larger set of recommended songs, shuffles them, and starts playback.
     */
    fun playRandomMix() {
        viewModelScope.launch {
            try {
                _uiState.update { it.copy(isLoading = true) }
                // Fetch a broader pool of recommendations (e.g., 50 songs)
                val recommendations = recommendationEngine.getPersonalizedRecommendations(50)
                if (recommendations.isNotEmpty()) {
                    val shuffled = recommendations.shuffled()
                    musicPlayer.playSong(shuffled[0], shuffled, 0)
                } else {
                    _uiState.update { it.copy(error = "No recommendations available for a random mix") }
                }
            } catch (e: Exception) {
                _uiState.update { it.copy(error = "Failed to start random mix") }
            } finally {
                _uiState.update { it.copy(isLoading = false) }
            }
        }
    }

    // ============================================================================================
    // Genre-Based Recommendation Sections
    // ============================================================================================

    /**
     * Load genre-based discovery sections using the user's taste profile.
     * Creates "Because you like [genre]" sections for top 3 genres.
     */
    private fun loadGenreSections() {
        viewModelScope.launch {
            try {
                val sections = recommendationEngine.getGenreBasedSections()
                _uiState.update { it.copy(genreSections = sections) }
            } catch (e: Exception) {
                _uiState.update { it.copy(genreSections = emptyList()) }
            }
        }
    }

    // ============================================================================================
    // Context-Aware Sections
    // ============================================================================================

    /**
     * Load context-aware sections based on time-of-day, day-of-week, and listening patterns.
     */
    private fun loadContextSections() {
        viewModelScope.launch {
            try {
                val sections = recommendationEngine.getContextAwareSections()
                _uiState.update { it.copy(contextSections = sections) }
            } catch (e: Exception) {
                _uiState.update { it.copy(contextSections = emptyList()) }
            }
        }
    }

    // ============================================================================================
    // Mood Detection
    // ============================================================================================

    /**
     * Detect the user's current mood from recent listening patterns.
     */
    private fun detectMood() {
        viewModelScope.launch {
            try {
                val mood = recommendationEngine.detectCurrentMood()
                _uiState.update { it.copy(detectedMood = mood) }
            } catch (_: Exception) { }
        }
    }

    // ============================================================================================
    // Infinite Scroll — Load More
    // ============================================================================================

    /**
     * Load additional personalized sections for infinite scrolling.
     * Called when user reaches the bottom of the LazyColumn.
     */
    private var loadMoreRetryCount = 0
    private val maxLoadMoreRetries = 3

    fun loadMore() {
        val currentState = _uiState.value
        if (currentState.isLoadingMore || currentState.hasReachedEnd) return

        viewModelScope.launch {
            _uiState.update { it.copy(isLoadingMore = true) }
            try {
                val page = currentState.loadMorePage + 1
                val newSections = recommendationEngine.getMoreSections(
                    page = page,
                    existingTitles = collectAllTitles()
                )
                if (newSections.isEmpty()) {
                    _uiState.update { it.copy(isLoadingMore = false, hasReachedEnd = true) }
                } else {
                    loadMoreRetryCount = 0 // Reset on success
                    _uiState.update {
                        it.copy(
                            moreSections = it.moreSections + newSections,
                            isLoadingMore = false,
                            loadMorePage = page
                        )
                    }
                }
            } catch (e: Exception) {
                _uiState.update { it.copy(isLoadingMore = false) }
                // Auto-retry on error (up to 3 times) with increasing delay
                if (loadMoreRetryCount < maxLoadMoreRetries) {
                    loadMoreRetryCount++
                    kotlinx.coroutines.delay(1500L * loadMoreRetryCount)
                    loadMore()
                }
            }
        }
    }

    /**
     * Collect all existing section titles to avoid duplicate sections during load-more.
     */
    private fun collectAllTitles(): Set<String> {
        val state = _uiState.value
        val titles = mutableSetOf<String>()
        state.homeSections.mapTo(titles) { it.title }
        state.filteredSections.mapTo(titles) { it.title }
        state.personalizedSections.mapTo(titles) { it.title }
        state.genreSections.mapTo(titles) { it.title }
        state.contextSections.mapTo(titles) { it.title }
        state.moreSections.mapTo(titles) { it.title }
        return titles
    }
}
